// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/Article.vue')['default']
    ArticleSidebar: typeof import('./src/components/articleSidebar/articleSidebar.vue')['default']
    Author: typeof import('./src/components/Author/Author.vue')['default']
    Classics: typeof import('./src/components/article/Classics.vue')['default']
    Empty: typeof import('./src/components/empty/empty.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    LoadMore: typeof import('./src/components/LoadMore/LoadMore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper/Swiper.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/Typewriter.vue')['default']
  }
}
