// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article/Article.vue')['default']
    Author: typeof import('./src/components/Sideways/Author.vue')['default']
    Classics: typeof import('./src/components/List/Classics.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    Copyright: typeof import('./src/components/Article/components/Copyright.vue')['default']
    Directory: typeof import('./src/components/Sideways/Directory.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Emote: typeof import('./src/components/Comment/components/Emote/index.vue')['default']
    Empty: typeof import('./src/components/Empty/Empty.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    Frame: typeof import('./src/components/Frame/Frame.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    HotArticle: typeof import('./src/components/Sideways/HotArticle.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    List: typeof import('./src/components/Comment/components/List/index.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    LoadMore: typeof import('./src/components/LoadMore/LoadMore.vue')['default']
    NewComments: typeof import('./src/components/Sideways/NewComments.vue')['default']
    Nprogress: typeof import('./src/components/Nprogress/Nprogress.vue')['default']
    RandomArticle: typeof import('./src/components/RandomArticle/RandomArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper/Swiper.vue')['default']
    Tag: typeof import('./src/components/Article/components/Tag.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar/ToolBar.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/Typewriter.vue')['default']
    UpAndDown: typeof import('./src/components/Article/components/UpAndDown.vue')['default']
  }
}
